extensions:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  collectd:
    endpoint: 0.0.0.0:8081
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  otlp:
    protocols:
      grpc:
      http:
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
  zipkin:

processors:
  batch:
  # Optional: The following processor can be used to add a default "deployment.environment" attribute to the logs and 
  # traces when it's not populated by instrumentation libraries.
  # If enabled, make sure to enable this processor in the pipeline below.
  #resource/add_environment:
    #attributes:
      #- action: insert
        #value: staging/production/...
        #key: deployment.environment

exporters:
  # Metrics
  prometheus:
    endpoint: 0.0.0.0:9090
  # Traces
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  # Debug
  logging:
    #loglevel: debug

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [jaeger, otlp, zipkin]
      processors:
      - batch
      #- resource/add_environment
      exporters: [jaeger, logging]
